# define two variables 'dockerId' and 'dockerPassword' in the build pipeline in UI for your ACR credentials
trigger:
  batch: true
  branches:
    include:
    - development
jobs:
- template: ../../azure-pipelines.template.yml
  parameters:
    language: 'dotnetcore'